# Generated by Django 6.0.2 on 2026-02-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cp',
            field=models.IntegerField(choices=[(0, 'Typical Angina'), (1, 'Atypical Angina'), (2, 'Non-anginal Pain'), (3, 'Asymptomatic')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Female'), (1, 'Male')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='slope',
            field=models.IntegerField(choices=[(0, 'Upsloping'), (1, 'Flat'), (2, 'Downsloping')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='thal',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Fixed Defect'), (3, 'Reversable Defect')]),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['created_at'], name='api_patient_created_b5d741_idx'),
        ),
    ]
