# Generated by Django 6.0.2 on 2026-02-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_patient_options_alter_patient_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='api_patient_created_b5d741_idx',
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='risk_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
