# Generated by Django 6.0.2 on 2026-02-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='risk_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='slope',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='thal',
            field=models.IntegerField(),
        ),
    ]
